### ISSUE TITLE
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'forkProperties' for extension 'openApi' of type org.springdoc.openapi.gradle.plugin.OpenApiExtension.

### ISSUE THREAD

**Issue by 9106234** [springdoc/springdoc-openapi-gradle-plugin#104]
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'forkProperties' for extension 'openApi' of type org.springdoc.openapi.gradle.plugin.OpenApiExtension.

I get the above exception for my gradle build with the latest  id 'org.springdoc.openapi-gradle-plugin' version '1.6.0'
with old version 1.3.3 I dont have that issue.
How do I fix it?

This is required for upgrade to java 17.
I dont have forkProperties defined in my gradle build

**Comment by velmurugantdvm** [comment]
forkProperties has been removed in the recent version. Hence we should apply below code to replace it I guess.
```
 bootRun {
        systemProperties System.properties
    }
```
