### ISSUE TITLE
generateOpenApiDocs is wrongly considered as "up-to-date" by gradle 8.0

### ISSUE THREAD

**Issue by LaFrimousse** [springdoc/springdoc-openapi-gradle-plugin#106]
Hi, 

With gradle 8.0.2 and the version 1.6.0 of this plugin, I have experienced the following issue:

1.  I run ```$ ./gradlew generateOpenApiDocs``` and the openApi.json file is correctly generated.
2. I then change the source code of one of my .java files (for example the URL of one of my @RestController)
4. Running again ```$ ./gradlew generateOpenApiDocs``` does not re-generate the openApi.json, because the task is wrongly considered as "up-to-date" by gradle. 

In fact, the only way I found to regenerate the openApi.json file is to delete the existing file before regenerating it. 
Is that a known issue ?

Thanks for all.

**Comment by bnasslahsen** [comment]
@LaFrimousse m,

You should run `clean` before.

**Comment by LaFrimousse** [comment]
@bnasslahsen thanks for your answer. 

Running ```clean``` before ```generateOpenApiDocs``` is more or less what I was already doing:  deleting the existing openApi.json file before regenerating it.  However, this is not ideal.

Let's consider the following pipeline that I would like to automate with gradle:
1. Compiling my spring boot MVC application.
2. Running ```generateOpenApiDocs``` to build an openApi.json file from it.
3. Generate a TypeScript client from this file, using https://openapi-generator.tech
4. Compile the client application.

I want all of this to be executed when I run the gradle ```build``` task, and I do not want to have to wonder if I need to run the ```clean``` task before that. (And I do not want to run it all the time for efficiency.)

Hence, is it possible to change the conditions that makes gradle consider the ```generateOpenApiDocs``` task to be up to date ?  For instance, the gradle ```compile``` task (from java plugin) is run only when the source files have change. Such a behaviour for the ```generateOpenApiDocs``` would be great ! 

What do you think ? 
Should we reopen the issue ?

**Comment by tehrnhoefer** [comment]
I would also be very much interested in a response  to @LaFrimousse's point as it seems counter-intuitive to have to clean

**Comment by LaFrimousse** [comment]
@tehrnhoefer I just reopened the issue[issue#107](https://github.com/springdoc/springdoc-openapi-gradle-plugin/issues/107)

**Comment by hiddewie** [comment]
I created a pull request that configures the inputs to match the Spring Boot run task, which should solve this issue: https://github.com/springdoc/springdoc-openapi-gradle-plugin/pull/147
