### ISSUE TITLE
generateOpenApiDocs is wrongly considered as "up-to-date" by gradle 8.0

### ISSUE THREAD

**Issue by LaFrimousse** [springdoc/springdoc-openapi-gradle-plugin#107]
Hi,

With gradle 8.0.2 and the version 1.6.0 of this plugin, I have experienced the following issue:

1. I run  ```$ ./gradlew generateOpenApiDocs```  and the openApi.json file is correctly generated.
2. I then change the source code of one of my .java files (for example the URL of one of my @RestController)
3. Running again ```$ ./gradlew generateOpenApiDocs``` does not re-generate the openApi.json, because the task is wrongly considered as "up-to-date" by gradle. 

The actual solution to my problem is to delete the current openApi.json file ( ```$ ./gradlew clean``` can be tuned to do the trick) before running the ```$ ./gradlew generateOpenApiDocs``` task again. However, **this is not an optimal behaviour**. 

I would like to automate the following build pipeline on a project:
1. Compiling a spring boot MVC application.
2. Running generateOpenApiDocs to build an openApi.json file from it.
3. Generate a TypeScript client from the openApi.json file, using the [openAPI Generator](https://openapi-generator.tech) project.
4.  Compile the client (Typescript) application.

 I want all of the above to be executed when I run the gradlew ```build``` task, and I do not want to have to wonder if I need to run the ```clean``` task before that. (And I do not want to run it all the time for efficiency.)

Thus, I'm wondering if it is possible for you to change the conditions that makes gradle consider the generateOpenApiDocs task to be up to date ? Perhaps you can be inspired by the gradle ```compile``` task from the official java plugin. This task is run only when the source code did change.  Such a behaviour for the generateOpenApiDocs task would be really great ! 

I hope I have convinced you of the usefulness of this fix.

Thanks for your time.

**Comment by ruoat** [comment]
Hi, this is how we have mitigated the issue
```
// Generate the documentation always when task is run
tasks.whenTaskAdded {
    if (name.contains("generateOpenApiDocs")) {
        outputs.upToDateWhen { false }
    }
}
```

**Comment by LaFrimousse** [comment]
Hi, and thanks for spending time on this issue ;-).

I'm by far not a gradle expert, but doesn't the above code implies that from now one, the ```generateOpenApiDocs``` will never be considered up-to-date ? 

Running ```generateOpenApiDocs``` for every build will slow down the build unnecessarily.

**Comment by ruoat** [comment]
Hi, I am just using the plugin and not contributor so don't have deep knowledge about the issue. Yes, it always builds so our solution is not optimal. Hopefully someone finds a better way!

**Comment by nbrugger-tgm** [comment]
@bnasslahsen  whats the reason for flagging this as `wontfix` and closing it?
Why won't it be fixed? Is there a suggested workaround? Do you think its a non issue?
Just closing an issue without any comment beside adding `wontfix` leaves us all in the dark
