### ISSUE TITLE
OpenApiDocs fails with WebFlux application and Gradle

### ISSUE THREAD

**Issue by mertyertugrul** [springdoc/springdoc-openapi-gradle-plugin#111]
Hi,

I on my Webflux reactive applications that builds with Gradle I cannot make it work "/swagger-ui.html" It keeps making
```
Whitelabel Error Page
This application has no configured error view, so you are seeing this as a fallback.
```
But it works with Maven.

Here is my build.gradle file.

```
plugins {
    id 'java'
    id 'org.springframework.boot' version '3.0.6'
    id 'io.spring.dependency-management' version '1.1.0'
    id 'com.github.johnrengelman.processes' version '0.5.0'
    id 'org.springdoc.openapi-gradle-plugin' version '1.6.0'
}

group = 'com.mertyertugrul'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '17'

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb-reactive'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'io.projectreactor:reactor-test'
    implementation 'org.springdoc:springdoc-openapi-webflux-ui:1.7.0'
    implementation 'org.springdoc:springdoc-openapi-webflux-core:1.7.0'
    implementation "io.swagger.core.v3:swagger-annotations:2.2.9"
    implementation "io.swagger.core.v3:swagger-models:2.2.9"
}

tasks.named('test') {
    useJUnitPlatform()
}
```

I read the [issued](https://github.com/springdoc/springdoc-openapi-gradle-plugin/issues/10) that is closed previously. It is not working anymore it might be version issue.

Here is my code https://github.com/mertyertugrul/swagger-ui-test

Any idea what I am doing wrong?

Kind Regards

**Comment by mertyertugrul** [comment]
@istibekesi Yes I tried the suggested answer but no luck. Still _**"Whitelabel Error Page"**_

**Comment by bnasslahsen** [comment]
For spring-boot 3. use [springdoc-openapi v2.x]( https://springdoc.org/)
And use `id 'org.springdoc.openapi-gradle-plugin' version '1.7.0'`

**Comment by AlbertSnows** [comment]
Hi I'm commenting on this in case anyone else stumbles across this issue when trying to get openapi working with webflux and gradle. 
The `springdoc-openapi-gradle-plugin` is so you can run the `generateOpenApiDocs` task. You don't need it to generate the swagger ui for your endpoints. 
If you're just trying to get the ui and api-docs working, you should only need two dependencies (+ java and boot plugins)
```
    implementation 'org.springframework.boot:spring-boot-starter-webflux:3.0.0'
    implementation 'org.springdoc:springdoc-openapi-starter-webflux-ui:2.0.2'
```
api docs is `http://localhost:8080/v3/api-docs`
ui is `http://localhost:8080/webjars/swagger-ui/index.html`
