### ISSUE TITLE
How to generate yaml with generateOpenApiDocs

### ISSUE THREAD

**Issue by spartanhooah** [springdoc/springdoc-openapi-gradle-plugin#113]
I see [this similar issue](https://github.com/springdoc/springdoc-openapi-gradle-plugin/issues/13) that was closed with a pull request. I tried the same configuration as in the issue, but I still get a file that has the `yaml` extension but is actually JSON. How can I get this task to actually generate yaml?

**Comment by axaratox** [comment]
> I see [this similar issue](https://github.com/springdoc/springdoc-openapi-gradle-plugin/issues/13) that was closed with a pull request. I tried the same configuration as in the issue, but I still get a file that has the `yaml` extension but is actually JSON. How can I get this task to actually generate yaml?

For me it worked with this configuration:
```
openApi {
    apiDocsUrl.set("http://localhost:8080/v3/api-docs.yaml")
    outputFileName.set("openapi.yaml")
}
```
Plugin version 1.6.0, `springdoc-openapi-starter-webmvc-ui` version 2.1.0, Spring Boot version 3.0. Hope it will help you.

**Comment by spartanhooah** [comment]
Thanks, that worked like a charm!
