### ISSUE TITLE
outputFileName extension is ignored

### ISSUE THREAD

**Issue by kkocel** [springdoc/springdoc-openapi-gradle-plugin#122]
According to the documentation `outputFileName` - `Specifies the output file name and format. Use extension .yaml for YAML output, .json for JSON output`

The problem is that in the code the wrong value is checked:
<img width="1347" alt="image" src="https://github.com/springdoc/springdoc-openapi-gradle-plugin/assets/454412/8d084103-dd6a-40a0-b3de-31a0c8c143a1">

The proper way is to validate `fileName` instead of `url`

**Comment by bnasslahsen** [comment]
The proper way is to use the URL.
Documentation is updated. 
https://github.com/springdoc/springdoc-openapi-gradle-plugin/commit/361acfd95106238d6deeb824e91f709d81085739
