### ISSUE TITLE
Setting task dependency leads to settings being ignored

### ISSUE THREAD

**Issue by rechvs** [springdoc/springdoc-openapi-gradle-plugin#123]
### Description of the problem
Since [the docs](https://github.com/springdoc/springdoc-openapi-gradle-plugin/blob/fff1285081defcf4864f4c7ec1007ff551b08f4e/README.md#how-the-plugin-works) recommend to always execute `gradle clean generateOpenApiDocs`, it seems sensible to configure the appropriate task dependencies, so that `clean` is always automatically executed before `generateOpenApiDocs`. However, with version 1.7.0 this leads to custom settings being ignored.

### Example project

Link: https://github.com/rechvs/springdoc-openapi-gradle-plugin-Issue123

The project declares a task dependency (Gradle Kotlin DSL):
```kotlin
tasks {
  withType(OpenApiGeneratorTask::class.java) {
    dependsOn(clean)
  }
}
```
Additionally, the project uses the following extension settings:
```kotlin
openApi {
  outputDir = projectDir.resolve("openapi")
  outputFileName = "my-openapi.json"
}
```
### Expected result
The `generateOpenApiDocs` task generates the file `openapi/my-openapi.json`.

### Actual result
The `generateOpenApiDocs` task generates the file `build/openapi.json`, i.e., the custom settings for `outputDir` and `outputFileName` are ignored.

**Comment by rechvs** [comment]
Judging by [this comment](https://github.com/springdoc/springdoc-openapi-gradle-plugin/issues/117#issuecomment-1683543772) I guess this is expected behavior. I can at least confirm that specifying the `openApi {...}` before the `tasks {...}` block is a viable workaround.

**Comment by hiddewie** [comment]
This might be solved by the PR in https://github.com/springdoc/springdoc-openapi-gradle-plugin/pull/147, which sets the inputs of the OpenAPI generation task to the same inputs as the Spring Boot run task. That will remove the need to clean the OpenAPI output entirely, because the plugin will regenerate the file if the source code changes.
