### ISSUE TITLE
YAML not supported

### ISSUE THREAD

**Issue by gnuton** [springdoc/springdoc-openapi-gradle-plugin#13]
Hi,
I would need to generate swagger files in yaml,
SpringDoc supports it but not this plugin.

When I run it with the following config:
```
openApi {
    apiDocsUrl.set("http://localhost:8080/api-docs.yaml")
    outputDir.set(file("$buildDir/docs"))
    outputFileName.set("swagger.yaml")
    waitTimeInSeconds.set(10)
}

```
the plugin fails with
```
* What went wrong:
Execution failed for task ':generateOpenApiDocs'.
> A JSONObject text must begin with '{' at 1 [character 2 line 1]


```
https://github.com/springdoc/springdoc-openapi-gradle-plugin/blob/master/src/main/kotlin/org/springdoc/openapi/gradle/plugin/OpenApiGeneratorTask.kt#L64

**Comment by kpramesh2212** [comment]
@gnuton 

Yes at present we only support JSON but support for yaml can be added.

**Comment by gnuton** [comment]
is there any update on this? I may help if needed
