### ISSUE TITLE
Proposed customBootRun configuration to pass Spring Active Profiles does not work for me

### ISSUE THREAD

**Issue by mpolonio** [springdoc/springdoc-openapi-gradle-plugin#132]
This configuration does not work for me:
    customBootRun {
        args.set(["--spring.profiles.active=special"]) 
    }
But after analysing plugin code I came up with this solution that actually works:
    customBootRun {
        environment['SPRING_PROFILES_ACTIVE'] = 'local'
    }

**Comment by bnasslahsen** [comment]
@mpolonio,

The following is just working fine:
```yaml
                customBootRun {
                    args = ["--spring.profiles.active= local"]
                }
```
