### ISSUE TITLE
add property method which allows to set SPRING_BOOT_RUN_TASK_NAME to a user-defined one

### ISSUE THREAD

**Issue by MichaelKoch11** [springdoc/springdoc-openapi-gradle-plugin#133]
It would be a nice feature if you could define a property for the Open-APi-Doc deployment task to overwrite SPRING_BOOT_RUN_TASK_NAME .
This is useful, for example, if you start the Api-Doc generation in a task that is not the bootRun and is, for example, a task for local execution.

**Comment by bnasslahsen** [comment]
@MichaelKoch11,

There are no plans to support this feature.
