### ISSUE TITLE
Pass basic auth parameter to task

### ISSUE THREAD

**Issue by vonWojtas** [springdoc/springdoc-openapi-gradle-plugin#134]
Hey ! 

I would like to know your best practice for following scenario: 

The swagger endpoint is protected with basic auth.
How could I pass username and password for the task to access the open api docs?

Or should I re-configure my setup?

I have a Spring Boot 3, Kotlin, regular WebMVC application and want to generate docs.

Thank you very much in advance for any possible help :)

**Comment by Donquih0te** [comment]
I guess there is currently no way to specify the authentication type and credentials.
https://github.com/springdoc/springdoc-openapi-gradle-plugin/blob/e855f9c3aeb776f3d3ef285c80aca748c5a50950/src/main/kotlin/org/springdoc/openapi/gradle/plugin/OpenApiGeneratorTask.kt#L77-L80

**Comment by vonWojtas** [comment]
mhm. do you have an idea how I could do it easily anyways? 🤔

**Comment by japzio** [comment]
current open PR https://github.com/springdoc/springdoc-openapi-gradle-plugin/pull/144 , might also apply to this use-case

**Comment by bnasslahsen** [comment]
https://github.com/springdoc/springdoc-openapi-gradle-plugin/pull/144 should resolve this issue.

**Comment by soid** [comment]
Example of setting it via #144 added headers:
```
openApi {
    apiDocsUrl.set("http://localhost:8079/v3/api-docs")
...
    requestHeaders = [
        // The hash is Base64 encoded "user:password" for logging in Swagger
        "Authorization": "Basic dXNlcjpwYXNzd29yZA=="
    ]
}
```
