### ISSUE TITLE
Does not work with spring boot 3.2.0

### ISSUE THREAD

**Issue by steklopod** [springdoc/springdoc-openapi-gradle-plugin#137]
<img width="2433" alt="Снимок экрана 2023-12-08 в 20 49 20" src="https://github.com/springdoc/springdoc-openapi-gradle-plugin/assets/29500153/d00d67fb-13e0-4e33-9299-026594bd5b4f">

**Comment by rechvs** [comment]
@steklopod Did you manage to get the plugin working with Spring Boot 3.x? I’m trying to do that but get

> \> Task :generateOpenApiDocs
> Unable to connect to http://localhost:8080/v3/api-docs waited for 30 seconds
