### ISSUE TITLE
Small enhancement - additional option to specify headers

### ISSUE THREAD

**Issue by japzio** [springdoc/springdoc-openapi-gradle-plugin#145]
Added requestHeaders map to be able to specify additional headers. Can be used if apidocs url is protected by basicAuth or setting custom url to generated openapi spec json|yaml
```
     requestHeaders = [
       "x-forwarded-host": "custom-host",
       "x-forwarded-port": "7000"
    ]
```

Ref feature https://github.com/springdoc/springdoc-openapi-maven-plugin

**Comment by japzio** [comment]
might need your review @bnasslahsen 
thanks

**Comment by bnasslahsen** [comment]
@japzio,

Changes merged to master.
You can test it
