### ISSUE TITLE
Download API Docs from a @SpringBootTest Context

### ISSUE THREAD

**Issue by Gentoli** [springdoc/springdoc-openapi-gradle-plugin#146]
Not particularly sure how to achieve this. This will be convenient for apps require external dependencies on startup, or/and it's not easy or redundant to create a extra profile with everything mocked/excluded.

There should usually a test with `@SpringBootTest`, that means there is a working fake context. Then `MockMvc` or a http client can be use to extract the docs.

**Comment by bnasslahsen** [comment]
@Gentoli,

There are no plans to support this feature

**Comment by Gentoli** [comment]
@bnasslahsen 

Can you elaborate a bit? Is this against the architecture of the plugin? Is the project not planning to take feature request? Are you going to reject PRs if this is implemented?

**Comment by bnasslahsen** [comment]
@Gentoli,

The project not planning to take feature request. 
But if you propose a PRs, we would be happy to consider them.
