### ISSUE TITLE
Name collision possible for colliding super type names

### ISSUE THREAD

**Issue by tbvh** [springdoc/springdoc-openapi-gradle-plugin#148]
In a project where we use polymorphism quite a lot we identified that supertypes with a shared name might collide. The springdoc output is therefore incorrect. 
An error should be raised instead, to prevent the possibility of publishing an inconsistent spec.

The issue arises when there exist two (or more) type hierarchies with a common supertype name and the supertypes are annotated with `@JsonSubTypes`. The resulting schema defines the subtypes with an `allOf` construct to specify the inherited properties. Where the schema is wrong is that only one of the supertype definitions is included. Subtypes of the other (not included) supertype reference the incorrect spec by name, while still referencing the supposed inherited properties (e.g. in the 'required' list).

For example, this is what the supertype and subtype mismatch in the schema can look like. Foo extends from the CollidingBase shown, but Bar actually has a different CollidingBase supertype:
```
  "components": {
    "schemas": {
      "CollidingBase": {
        "required": [
          "fooBase"
        ],
        "type": "object",
        "properties": {
          "fooBase": {
            "type": "string"
          }
        }
      },
      "Bar": {
        "required": [
          "bar",
          "barBase"
        ],
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/CollidingBase"
          },
          {
            "type": "object",
            "properties": {
              "bar": {
                "type": "string"
              }
            }
          }
        ]
      },
      "Foo": {
         [...]
      },
```

Versions:
org.springdoc:springdoc-openapi-starter-webmvc-ui version 2.5.0
org.springframework.boot version "3.3.0"

Example repository here: https://github.com/tbvh/springdoc-collision-demo (the full api-docs output is in the repo).

**Comment by bnasslahsen** [comment]
@tbvh,

This issue is not relevant for [springdoc-openapi-gradle-plugin](https://github.com/springdoc/springdoc-openapi-gradle-plugin)
