### ISSUE TITLE
Adding new dependency to generateOpenApiDocs task

### ISSUE THREAD

**Issue by Andrew3431** [springdoc/springdoc-openapi-gradle-plugin#15]
The task `generateOpenApiDocs` fails with my code due to an error. I need to add another dependency to the generateOpenApiDocs task to make it work. Is there a way I can an additional dependency to this task.

**Comment by gnuton** [comment]
If I got it right you can solve you issue by adding something like this to your build.gradle
generateOpenApiDocs.dependsOn yourTaskHere
