### ISSUE TITLE
Release Version: 1.1.0

### ISSUE THREAD

**Issue by bnasslahsen** [springdoc/springdoc-openapi-gradle-plugin#18]
This ticket is to follow the release v1.1.0

**Comment by kpramesh2212** [comment]
@bnasslahsen 

Released  1.1.0 to gradle plugin portal

Release process is simple 

Once you claim the plugin from the gradle plugin portal 

1. Generate api keys and add it to your ~/.gradle/gradle.properties
gradle.publish.key=<your key>
gradle.publish.secret=<your secret>

2. Run gradle clean build 

3. Run gradle publishPlugins

Thats it

**Comment by bnasslahsen** [comment]
Thank you @kpramesh2212 for the support.
The release is now available on the gradle portal.
