### ISSUE TITLE
generateOpenApiDocs task can not find the certificate in HTTPS environment

### ISSUE THREAD

**Issue by HomoEfficio** [springdoc/springdoc-openapi-gradle-plugin#21]
I have PKCS12 certificate in `src/main/resources/keystore` directory and I can successfully access the root via `https://localhost:8443'.

But when I execute 'openapi > generateOpenApiDocs' gradle task, it shows error like below:

```
* What went wrong:
Execution failed for task ':generateOpenApiDocs'.
> javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
My dev environment:
- OpenJDK 14
- Spring Boot 2.3
- Gradle 6.4.1
- openapi-gradle-plugin 1.2.0

I guess 'forkedSpringBootRun' task can not find the certificate.

**Comment by gnuton** [comment]
Not sure what's the sense of having certificates for localhost, but beside that I think the fix should not come from the plugin, but you have to create an application local with your local settings.

**Comment by HomoEfficio** [comment]
We can have private certificates in localhost to support HTTPS in development environment.

I already avoid this problem by setting up another profile which does not use HTTPS and by specifying that profile when I executed generateOpenApiDocs task.

The reason why I post this issue is that it would be far more convenient if I could specify the certificate location in the customization, for example:

```
openApi {
    certPath.set("path/to/certificate")
    ...
```

Anyway, thanks for the nice plugin!

**Comment by hemadri** [comment]
I have similar issue while generating the api docs, 
Connecting to localhost with SSL isn't working.
Need a fix for this.
`javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No name matching localhost found`

**Comment by bnasslahsen** [comment]
@hemadri, @HomoEfficio, 

This is related to your local SSL configuration. Here are some tips:

 - Make sure you have imported the certificate to your JDK trustore.
 - The JDK trustore should be the same as used by your maven.
 - On your CN, make sure you declare localhost.
 - When you run gradle command don't forget to add:

In your gradle.properties::

```propeerties
systemProp.javax.net.ssl.trustStore=cacerts
systemProp.javax.net.ssl.trustStorePassword=changeit
```

Or in your build.gradle:

```gradle
System.setProperty('javax.net.ssl.trustStore', '/path/to/my-file.jks')
System.setProperty('javax.net.ssl.trustStorePassword', 'my-pass')
```
