### ISSUE TITLE
Allow `-D` options to be passed to forked spring boot

### ISSUE THREAD

**Issue by cah-nathanzender** [springdoc/springdoc-openapi-gradle-plugin#22]
I have an application that requires spring profiles to be set to run locally. This means that when I try to run the task when it spins up the app but of course it does not work. 

What i run now
`./gradlew generateOpenApiDocs`

Suggestions 

Allow passing in them from whatever is passed to gradle
`./gradlew generateOpenApiDocs -Dspring.profiles.active=localdb,otherprofile,etc`

Although this might also requires configuration at the task level...see here
https://mrhaki.blogspot.com/2015/09/gradle-goodness-pass-java-system.html

So maybe making it a configuration option makes it easier/more straight forward. 
```
openApi {
    forkedSystemProperties = "-Dspring.profiles.active=localdb,otherprofile,etc"
}
```

I'm willing to help with a PR just would be interested in feedback on what direction feels like the better option.

**Comment by zendern** [comment]
Was able to pretty easily get both options originally mentioned in PR #23

**Comment by bnasslahsen** [comment]
v1.3.0 is now released and integrates the proposed PR from @zendern.
