### ISSUE TITLE
How to apply to subprojects only?

### ISSUE THREAD

**Issue by martin-walsh** [springdoc/springdoc-openapi-gradle-plugin#24]
Gradle 6.1.1
Spring Boot 2.2.5.RELEASE

After adding plugins block
```
plugins {
    id "com.github.johnrengelman.processes" version "0.5.0"
    id "org.springdoc.openapi-gradle-plugin" version "1.3.0"
}
```

all gradle commands fail with the following error:

`Task with name 'bootJar' not found in root project`

Is this plugin usable with a multi module gradle project

e.g.
```
buildscript {
    ext {
        springBootVersion = '2.2.5.RELEASE'
    }
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
    }
}

plugins {
    id "net.ossindex.audit" version "0.4.11"
    id "com.github.johnrengelman.processes" version "0.5.0"
    id "org.springdoc.openapi-gradle-plugin" version "1.3.0"
}

subprojects {
    apply plugin: 'net.ossindex.audit'
    apply plugin: 'org.springdoc.openapi-gradle-plugin'
    apply plugin: 'org.springframework.boot'
    apply plugin: 'io.spring.dependency-management'

    sourceCompatibility = 13

    group = 'com.example'
    version = '2.9.0'

   // dependencies, repositories etc
```

**Comment by martin-walsh** [comment]
One hacky workaround is to declare the bootJar task at the root project level

```
task bootJar(type: DefaultTask) // This is a workaround for "org.springdoc.openapi-gradle-plugin"
```

**Comment by kpramesh2212** [comment]
your hack is not correct

What you need to do in this case is


buildscript {
    ext {
        springBootVersion = '2.2.5.RELEASE'
    }
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
    }
}

plugins {
    id "net.ossindex.audit" version "0.4.11"
    id "com.github.johnrengelman.processes" version "0.5.0" apply false
    id "org.springdoc.openapi-gradle-plugin" version "1.3.0" apply false
}

subprojects {
    apply plugin: 'net.ossindex.audit'
    apply plugin: 'com.github.johnrengelman.processes'
    apply plugin: 'org.springdoc.openapi-gradle-plugin'
    apply plugin: 'org.springframework.boot'
    apply plugin: 'io.spring.dependency-management'

    sourceCompatibility = 13

    group = 'com.example'
    version = '2.9.0'

**Comment by gaetjen** [comment]
I have a similar problem. For bootJar task I get the error "> Main class name has not been configured and it could not be resolved".
Using the `apply false`  resolves the issue, but then it is no longer possible to configure the `openApi` extension in the root `build.gradle.kts`.

```koltin
plugins {
    id("com.github.johnrengelman.processes") version "0.5.0" apply false
    id("org.springdoc.openapi-gradle-plugin") version "1.3.0" apply false
    id("org.springframework.boot") version "2.3.4.RELEASE" apply false
}

subprojects {
    apply {
            plugin("org.springframework.boot")
            plugin("com.github.johnrengelman.processes")
            plugin("org.springdoc.openapi-gradle-plugin")
        }

    openApi {
            waitTimeInSeconds.set(240)
            forkProperties.set("-Dspring.profiles.active=test -Deureka.client.enabled=false")
        }
}
```

This results in "Unresolved reference: openApi".

How can I avoid copying the same openApi configuration to every single subproject's `build.gradle.kts`?

**Comment by kpramesh2212** [comment]
try the following


```
plugins {
    id("com.github.johnrengelman.processes") version "0.5.0" apply false
    id("org.springdoc.openapi-gradle-plugin") version "1.3.0" apply false
    id("org.springframework.boot") version "2.3.4.RELEASE" apply false
}

subprojects {
    apply(plugin = "java")
    apply(plugin = "com.github.johnrengelman.processes")
    apply(plugin = "org.springdoc.openapi-gradle-plugin")
    apply(plugin = "org.springframework.boot")

    configure<org.springdoc.openapi.gradle.plugin.OpenApiExtension> {
        waitTimeInSeconds.set(240)
        forkProperties.set("-Dspring.profiles.active=test -Deureka.client.enabled=false")
    }
}
```
