### ISSUE TITLE
File is not overwritten unless explicitly removed first

### ISSUE THREAD

**Issue by martin-walsh** [springdoc/springdoc-openapi-gradle-plugin#25]
Running with

```
    openApi {
        apiDocsUrl.set("http://localhost:8080/v3/api-docs.yaml")
        outputDir.set(file("$projectDir/doc"))
        outputFileName.set("swagger.yaml")
    }
```

and changing some content does not result in changes to the `swagger.yaml` file unless the file is explicitly rm'd first.

The default location (i.e. `build/openapi.json`) can be worked around as `gradle clean` wipes it out, but what to do with a custom location e.g. in `doc/` dir for check in to source control

**Comment by martin-walsh** [comment]
@bnasslahsen Any suggestions?

**Comment by martin-walsh** [comment]
Found a workaround: `./gradlew generateOpenApiDocs --rerun-tasks`

**Comment by bnasslahsen** [comment]
This ticket is now closed, as there is workaround.

**Comment by danielsonjh** [comment]
Can this be built into the plugin to avoid the need for the workaround?

The simplest approach would be to add a `tasks.generateOpenApiDocs.dependsOn(tasks.clean)`, but that could be too destructive for some setups. Adding this would be more ok if it was behind a feature toggle, and was off by default.

It also seems like there should be a cleaner way to just destroy the output file to force it to re-run inside the plugin.

Another issue with this workaround `clean` task dependency workaround is that currently, the use of `project.afterEvaluate` in the plugin is causing some errors and confusion around how to set this up correctly outside the plugin. Details here https://github.com/springdoc/springdoc-openapi-gradle-plugin/issues/27#issuecomment-1244255710

**Comment by hiddewie** [comment]
This might be fixed by https://github.com/springdoc/springdoc-openapi-gradle-plugin/pull/147 I created to configure the inputs of the OpenAPI generation task as the Spring Boot run task. That will ensure changes in the source code will regenerate the OpenAPI file automatically, and do nothing if the sources did not change.
