### ISSUE TITLE
Method summary and parameter description missing in API or swagger-ui

### ISSUE THREAD

**Issue by farrukhnajmi** [springdoc/springdoc-openapi-gradle-plugin#26]
In my @RestController clases have io.swagger.annotations.Api, io.swagger.annotations.ApiOperation and io.swagger.annotations.ApiResponse annotations describing my methods, paremeters and responses. 

However, the API yaml and swagger-ui generated by the plugin doe snot seem to show any of the summary and description metadata that I assumed would be inferred from thoise annotations.

Is this currently unsupported or am I misisng some configuration for the plugin?

Please note that my server was generated from an openapi spec that already has all the metadata info using the [openapi-generator gradle plugin](https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator-gradle-plugin). I am using springdoc-openapi-gradle-plugin to provide the api and swagger-ui at runtime.

**Comment by bnasslahsen** [comment]
@farrukhnajmi, 

 The summary and description fields are already supported.
If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:

 - You need to describe your context (the title of an issue is not enough)
 - What version of spring-boot you are using?
 - What modules and versions of springdoc-openapi are you using? 
 - What are the actual and the expected result using OpenAPI Description (yml or json)?
 - **Provide with a sample code (HelloController) or Test that reproduces the problem**

**Comment by bnasslahsen** [comment]
Issue closed as no additional information provided.

**Comment by fuchengli1024** [comment]
I have same issue. the properties description all missing in the openapi document.
I am using spring boot 2.3.2.RELEASE and spring doc 1.5.10
