### ISSUE TITLE
generateOpenApiDocs HTTP call does not report errors

### ISSUE THREAD

**Issue by david-caldwell-idexx** [springdoc/springdoc-openapi-gradle-plugin#29]
I've added the plugin to a project in a multi-project build, and everything works until the last step -- the plugin starts a forked build, and the build waits for the incoming HTTP call, and then I get:

```
Unable to connect to http://127.0.0.1:11090/v3/api-docs waited for 30 seconds
org.awaitility.core.ConditionTimeoutException: Condition org.awaitility.kotlin.AwaitilityKt$sam$java_util_concurrent_Callable$0 was not fulfilled within 30 seconds.
```

But I can retrieve the URL from a browser (after the server starts but before the "timeout" terminates the Gradle task), so the plugin is successfully launching the server, and the server is successfully serving it.

Any ideas what might be going on here?.

**Comment by david-caldwell-idexx** [comment]
OK, the answer is that I'm getting a `401 Unauthorized`. I determined this by building the plugin from source and setting the log level on the HTTP call to debug, and then running Gradle with -Dorg.gradle.logging.level=debug.

I think it might be good to have a different error reporting strategy for these kinds of errors. The timeout language is somewhat misleading, and it would be good to emit, say, the result of the last attempt to distinguish what's wrong (`404 Not Found`? Connection refused?).

**Comment by david-caldwell-idexx** [comment]
I guess given that the server is protected with Basic authentication, this plugin can't currently be used on my project?

**Comment by songxiaocheng** [comment]
I solved my problem by turning off my network proxy.

**Comment by kpramesh2212** [comment]
Yeah at the moment we do ignore any exception that we get

            await ignoreException ConnectException::class withPollInterval Durations.ONE_SECOND atMost Duration.of(

May be for future releases we can add a logger to log those errors
