### ISSUE TITLE
Automatically start and stop spring boot application server while generating the open api json file.

### ISSUE THREAD

**Issue by kpramesh2212** [springdoc/springdoc-openapi-gradle-plugin#3]
springdoc-openapi-gradle plugin is manual.

In order for the plugin to work properly the spring boot application server needs to be started before hand manually via IDE.

This issue is a place holder for automating the start and stop process of the spring boot application server via a fork plugin.

**Comment by kpramesh2212** [comment]
This is done

**Comment by SanaKanji** [comment]
How did you solve this starting spring boot application issue?

**Comment by kpramesh2212** [comment]
I did it via process plugin

You can look at the source code

**Comment by SanaKanji** [comment]
can you provide a link to the source code you are referring to?

**Comment by kpramesh2212** [comment]
https://github.com/springdoc/springdoc-openapi-gradle-plugin/blob/master/src/main/kotlin/org/springdoc/openapi/gradle/plugin/OpenApiGradlePlugin.kt

Go through that code that contains the logic
