### ISSUE TITLE
Plugin with id 'com.github.johnrengelman.processes' not found.

### ISSUE THREAD

**Issue by timo-a** [springdoc/springdoc-openapi-gradle-plugin#33]
I added the line `id 'org.springdoc.openapi-gradle-plugin' version '1.3.0'` to my plugins block and got the following `Problem` in eclipse:

```
Could not run phased build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-6.6.1-bin.zip'.
Build file '.../myproject/build.gradle' line: 6
An exception occurred applying plugin request [id: 'org.springdoc.openapi-gradle-plugin', version: '1.3.0']
Failed to apply plugin 'org.springdoc.openapi-gradle-plugin'.
Plugin with id 'com.github.johnrengelman.processes' not found.
```

**Comment by kpramesh2212** [comment]
Sorry did you follow the docs you will have to add  that plugin yourself

paste your build.gradle file here

**Comment by timo-a** [comment]
I guess I didn't think the line `id("com.github.johnrengelman.processes") version "0.5.0"` was relevant. With it, it works.
