### ISSUE TITLE
Pure offline mode is possible?

### ISSUE THREAD

**Issue by vladimirfx** [springdoc/springdoc-openapi-gradle-plugin#34]
How to apply plugin to real project with external infrastructure dependencies like databases, message brokers and so on?
It is very inefficient to replicate working app to build doc artifacts...

**Comment by bnasslahsen** [comment]
@vladimirfx, 

You mock your external infrastructure, you don't need it to generate the API documentation.
 You should be something similar for your tests. You can reuse the same test spring profile for the API documentation generation in offline.

**Comment by vladimirfx** [comment]
Thank your for answer!
Actually we need documentation artifact and do it at build time usually. With JAX-RS and swagger we achieve this with easy. Moreover we use OpenApi to Asciidoc convertor and use this document in project documentation.
But with WebFlux it seems Springdoc is only option.
Can it be generated offline in principle?

P.S.: may stay this ticket open to other that migrating from other documentation generation solutions?

**Comment by bnasslahsen** [comment]
You can have a look at the existing plugins:
- https://springdoc.org/#plugins

If you have any enlacements, please feel free to propose a PR and we will have a look at it.
