### ISSUE TITLE
Unable to generate yaml format for a group 

### ISSUE THREAD

**Issue by jeff-lauterbach-by** [springdoc/springdoc-openapi-gradle-plugin#37]
I have multiple openapi specs in a single project and am using the `GroupedOpenApi` capability of springdoc.

I am trying to generate the openapi spec in yaml for a specific group through the gradle plugin by specifying the appropriate `apiDocsUrl` property.

I'm getting an error
```
A JSONObject text must begin with '{' at 1 [character 2 line 1]
```

I dug into the code and it is only looking at the end of the `apiDocsUrl` property to determine if it is yaml or not.  When using the Group capability, the yaml url format is like the following
`http://server:port/context-path/v3/api-docs.yaml/{groupName}`

The code should probably change to do a contains check instead of an endsWith.

**Comment by jeff-lauterbach-by** [comment]
Created pull request
https://github.com/springdoc/springdoc-openapi-gradle-plugin/pull/38

**Comment by YunaBraska** [comment]
@jeff-lauterbach-by I also have multiple `GroupedOpenApi`s but how did you solve to generate more than one group? BTW I am not a Gradle expert :(

**Comment by bnasslahsen** [comment]
Merge done for the PR #38
