### ISSUE TITLE
generateOpenApiDocs produces javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target 

### ISSUE THREAD

**Issue by majones713** [springdoc/springdoc-openapi-gradle-plugin#42]
When I run generateOpenApiDocs task the below error occurs:

> Task :generateOpenApiDocs FAILED
> Task :stopForkedSpringBoot

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateOpenApiDocs'.
> javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Usually when I see this I add cert to keystore which in this case is exported from browser when hitting https://localhost:8181/v3/api-docs.  Even when export cert and add to keystore the issues still persists.  

I'm using:

**Java version**: Java11 

**Plugins**:
id "org.springframework.boot" version "2.4.0"
id "com.github.johnrengelman.processes" version "0.5.0"
id "org.springdoc.openapi-gradle-plugin" version "1.3.0"

Also as a heads up the application started successfully as well:

Working Directory: my working directory
Gradle user home: my user home
Gradle Distribution: Gradle wrapper from target build
Gradle Version: 6.7.1
Java Home: /Users/user/.p2/pool/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.macosx.x86_64_14.0.2.v20200815-0932/jre
JVM Arguments: None
Program Arguments: None
Build Scans Enabled: false
Offline Mode Enabled: false
Gradle Tasks: generateOpenApiDocs

> Task :generateLombokConfig UP-TO-DATE
> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :bootJarMainClassName UP-TO-DATE
> Task :bootJar UP-TO-DATE
> Task :forkedSpringBootRun

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.4.0)

.
.
.
.
.
.
.17:19:59.928 [main] [34mINFO [0;39m [36mc.f.m.m.MdmLoaderApiApplication[0;39m - Started Application in 13.18 seconds (JVM running for 14.247)
> Task :generateOpenApiDocs FAILED
> Task :stopForkedSpringBoot

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateOpenApiDocs'.
> javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 16s
8 actionable tasks: 3 executed, 5 up-to-date

**Comment by bnasslahsen** [comment]
This is a duplicate of #21, which is already answred.
