### ISSUE TITLE
forkProperties not working with 2 or more args

### ISSUE THREAD

**Issue by majones713** [springdoc/springdoc-openapi-gradle-plugin#43]
Hi,

I have a open api configuration where I'm passing the following args:

forkProperties.set("-Djasypt.encryptor.password=mypwd -Dspring.profiles.active=test")

When I execute the above command the forked spring boot application doesn't pickup the profile arg:

11:09:49.268 [main] [34mINFO [0;39m [36mc.f.m.m.MdmLoaderApiApplication[0;39m - No active profile set, falling back to default profiles: default

If I swap the args like this:

forkProperties.set(" -Dspring.profiles.active=test -Djasypt.encryptor.password=mypwd")

it picks up the profile but not as expected as the profile its using is the profile name + the subsequent args:

11:18:45.132 [main] [34mINFO [0;39m [36mc.f.m.m.MdmLoaderApiApplication[0;39m - The following profiles are active: **test -Djasypt.encryptor.password=mypwd**

Somehow this parameter isn't working.  When we pass args through command "./gradle -Dspring.profiles.active=test -Djasypt.encryptor.password=mypwd" and use parameter this way things work:

forkProperties = System.properties

But this doesn't work using in openApi block in build.gradle using it this way:

forkProperties.set("-Djasypt.encryptor.password=mypwd -Dspring.profiles.active=test")

Java version:11
Plugin versions:

id "com.github.johnrengelman.processes" version "0.5.0"
id "org.springdoc.openapi-gradle-plugin" version "1.3.0"
id "org.springframework.boot" version "2.4.0"
id 'io.spring.dependency-management' version '1.0.10.RELEASE'

**Comment by bnasslahsen** [comment]
@majones713, 

 Your assumption doesn't look right.  Please see the following working test which uses 2 jvm args :
https://github.com/springdoc/springdoc-openapi-gradle-plugin/blob/79ac348f53854ec1220716eb79ac0b30d58b6b21/src/test/kotlin/org/springdoc/openapi/gradle/plugin/OpenApiGradlePluginTest.kt#L125-L144

If you believe you are facing a bug, please make sure you follow the [guidance](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc), by providing a minimal project with a test that shows the issue you are facing.
