### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by nhajratw** [springdoc/springdoc-openapi-gradle-plugin#54]
Hello -- any idea when you might be able to get a new release out? Waiting for the gradle 7.0 compatibility.

Thanks!

**Comment by t-h-e** [comment]
The issue is probably the dependency to [`com.github.johnrengelman.processes`](https://github.com/johnrengelman/gradle-processes) which has not been maintained since 2018. 😞

**Comment by bnasslahsen** [comment]
@nhajratw ,

The release `v1.3.2` of the plugin is now available on [gradle portal](https://plugins.gradle.org/plugin/org.springdoc.openapi-gradle-plugin).

**Comment by nhajratw** [comment]
awesome thanks!
