### ISSUE TITLE
waitTimeInSeconds explained as “Time to wait in seconds for your Spring Boot application to start” but actually it’s maximum time to keep calling api.

### ISSUE THREAD

**Issue by kogayushi** [springdoc/springdoc-openapi-gradle-plugin#55]
Hi

I might found documentation mistake.

according to [README](https://github.com/springdoc/springdoc-openapi-gradle-plugin/blob/de7748019427d251f1611b64930d5f9ae1c3ed29/README.md#customization), `waitTimeInSeconds` explained as “Time to wait in seconds for your Spring Boot application to start”. but, as I researched, it’s maximum time to keep trying to call spring boot's api rather than how long wait(sleep) before spring boot started.

corresponding source code is here.
https://github.com/springdoc/springdoc-openapi-gradle-plugin/blob/de7748019427d251f1611b64930d5f9ae1c3ed29/src/main/kotlin/org/springdoc/openapi/gradle/plugin/OpenApiGeneratorTask.kt#L66-L73

this DSL seems start polling soon, then keep trying to call api until satisfy "until" condition or elapsed over `waitTimeInSeconds`.

so I think, `waitTimeInSeconds`'s description should be like following at least.

> Maximum time to wait in seconds for your Spring Boot application started. after elapsed this time, gives up download the OpenAPI doc from `apiDocsUrl `.

further more, `waitTimeInSeconds` might mislead developers that it specify how long wait to start trying to download openapi specification.

so I prefer to rename `waitTimeInSeconds` to `maxWaitTimeInSeconds`.
but it might be a little bit troublesome work because we have to keep backward compatibility if do this work for patch version up.

best regards.

**Comment by bnasslahsen** [comment]
Thank you for your comments @kogayushi.
Feel free to propose a PR on the README, if you estimate you can bring more clarity for users.
