### ISSUE TITLE
Release the springdoc open api gradle plugin to the gradle plugin portal

### ISSUE THREAD

**Issue by kpramesh2212** [springdoc/springdoc-openapi-gradle-plugin#6]
This task is to release the springdoc open api gradle plugin.

**Comment by gnuton** [comment]
still missing? https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-gradle-plugin
Anyone working on this?

**Comment by kpramesh2212** [comment]
Hi 

I have already upload the plugin to plugin portal

https://plugins.gradle.org/plugin/org.springdoc.openapi-gradle-plugin

Out of curiosity why do you need the plugin to be upload the mvn centrol repository?

**Comment by dcp65** [comment]
It's a bit confusing that the 1.0.0 release doesn't appear under the [Releases](../releases) tab. 

It took me a while to figure out that there is at least one release of the plugin.

**Comment by iautushka** [comment]
Even more. The version in the `build.gradle` is still `version = "0.0.1-BETA"`.

**Comment by kpramesh2212** [comment]
Sorry I will update the build.gradle file and tag the release as 1.0.0

**Comment by gnuton** [comment]
actually no need for the plugin to appear in mvnrepository.com.
