### ISSUE TITLE
YAML not supported with actuator endpoint

### ISSUE THREAD

**Issue by brneto** [springdoc/springdoc-openapi-gradle-plugin#60]
I'd like to generate swagger files in yaml format, from actuator + openapi endpoints (http://localhost:8081/actuator/openapi/springdocDefault/yaml).

But run it with the following config:
```groovy
openApi {
	apiDocsUrl = 'http://localhost:8081/actuator/openapi/springdocDefault/yaml'
	outputFileName = 'openapi.yaml'
	outputDir =  file "$buildDir/docs"
}
```

I get the error:
```shell
* What went wrong:
Execution failed for task ':generateOpenApiDocs'.
> A JSONObject text must begin with '{' at 1 [character 2 line 1]
```

I see it had been added support to openapi default endpoint `http://localhost:8080/api-docs.yaml` (#13).

**Comment by brneto** [comment]
@bnasslahsen I had also added a pull request. But if you not happy with it you can remove it.

**Comment by brneto** [comment]
@bnasslahsen when are you planning to release a version with this fix?

**Comment by bnasslahsen** [comment]
by the end of the week.
