### ISSUE TITLE
Yaml spec file via api-docs.yaml url is not having parameters for fetching by groups using GroupedOpenApi

### ISSUE THREAD

**Issue by nandhae** [springdoc/springdoc-openapi-gradle-plugin#64]
When we use the plugin to generate yaml specs from code using the gradle task we are not being able to specify a URL parameter to fetch it using groups. We are only being able to download all the apis in a single file.

We use `groupedOpenApi` to achieve groups, it would be nice to have a way to generate yaml format spec for those specific groups.

**Comment by bnasslahsen** [comment]
for groups, use `groupedApiMappings` property.
