### ISSUE TITLE
Question about next version of the plugin (> 1.3.3)

### ISSUE THREAD

**Issue by trohr** [springdoc/springdoc-openapi-gradle-plugin#73]
Hello.

Version 1.3.3 of this plugin uses different tool to make forked process (that uses bootJar as I see it).
Version of this plugin from master uses task bootRun and different tool to make th forked process.

It seems to me that using the new way would likely help us solve some issues.

My question is: When do you plan on releasing the new version that is on master?

Thank you.

Sincerely yours,
Tomas Rohbacher

**Comment by bnasslahsen** [comment]
The fix is only compatible with Java 11.

We wait for the `gradle-execfork-plugin` release [that fixes](https://github.com/psxpaul/gradle-execfork-plugin/pull/44) this bug https://github.com/psxpaul/gradle-execfork-plugin/issues/40.

**Comment by trohr** [comment]
Hello.
I was asking when do you plan to release new version of your springdoc-openapi-gradle-plugin the will be made from code from your `master` branch.

Is the next release planned?
Thank you.
