### ISSUE TITLE
Readme has wrong Gradle instructions

### ISSUE THREAD

**Issue by bodiam** [springdoc/springdoc-openapi-gradle-plugin#74]
Now I understand why I was confused. The documentation in the README here (https://github.com/springdoc/springdoc-openapi-gradle-plugin) says:

Add the following:

```
plugins {
    id("org.springframework.boot") version "2.3.0.RELEASE"
    id("org.springdoc.openapi-gradle-plugin") version "1.3.3"
}
```

In the other documentation (https://springdoc.org/#gradle-plugin), it says: 

Add the following:

```
plugins {
      id("org.springframework.boot") version "2.3.0.RELEASE"
      id("com.github.johnrengelman.processes") version "0.5.0"
      id("org.springdoc.openapi-gradle-plugin") version "1.3.3"
}
```

The published documentation is correct, the readme is incorrect.

**Comment by bodiam** [comment]
Okay, logging a bug often helps. It seems I missed the `-ui` part in the dependency for some reason. It seems things are working now. The issue with the gradle process plugin is still there though

**Comment by bnasslahsen** [comment]
@bodiam, 

Read well the readme. it mentions `v1.3.4`

**Comment by bodiam** [comment]
Well, you changed the readme 9 days ago to correct it, and this issue is 23 days old :-) 

But thanks for fixing it!
