### ISSUE TITLE
fork properties not found

### ISSUE THREAD

**Issue by thejeff77** [springdoc/springdoc-openapi-gradle-plugin#75]
after upgrading from 1.3.3 to 1.3.4, get this error:

> Could not get unknown property 'forkProperties' for extension 'openApi' of type org.springdoc.openapi.gradle.plugin.OpenApiExtension.

application/build.gradle

config file:
```
openApi {
	waitTimeInSeconds.set(120)
	forkProperties.set("-Dspring.profiles.active=local")
	outputDir.set(file("$rootDir/application"))
	groupedApiMappings.set(["http://localhost:8080/v3/api-docs/someGroup1" : "someGroup1.json",
							"http://localhost:8080/v3/api-docs/someGroup2" : "someGroup2.json"])
}
```

**Comment by kogayushi** [comment]
hi, @thejeff77 

as far as i investigated, we should use `bootRun`'s `args` directive.
like this => https://github.com/springdoc/springdoc-openapi-gradle-plugin/blob/master/src/test/kotlin/org/springdoc/openapi/gradle/plugin/OpenApiGradlePluginTest.kt#L94-L96

probably, this is what you want to know.

**Comment by thejeff77** [comment]
Unfortunatly no. I'm not trying to set a local profile running the app. I'm trying to set it when the plugin runs - which is what this `forkProperties` argument is used for. It doesn't matter what app setting I set.. the point is that forkProperties is borked after the version upgrade - which is the reason for this bug. Does that make sense?

**Comment by kogayushi** [comment]
sorry, but i don’t understand your point.
anyway, did you try this ? not yet ?

if you try my suggestion, your config file gonna be like this.

```groovy
openApi {
	waitTimeInSeconds.set(120)
        bootRun {
            args = ["--spring.profiles.active= local"]
        }
	outputDir.set(file("$rootDir/application"))
	groupedApiMappings.set(["http://localhost:8080/v3/api-docs/someGroup1" : "someGroup1.json",
							"http://localhost:8080/v3/api-docs/someGroup2" : "someGroup2.json"])
}
```

i believe this gonna fix your issue, i don't know this is absolutely right way, though.

**Comment by kogayushi** [comment]
and, i forgot what i have to say.

i’m not maintainer of this plugin.
but  i’ve just found whom facing same issue what i was facing.

i hope my advice helps you, a little bit.

**Comment by sgrimm** [comment]
I ran into this too. My workaround:

```kotlin
import org.springframework.boot.gradle.tasks.run.BootRun

openApi {
  val bootRun = project.tasks["bootRun"] as BootRun

  // Previously: properties["spring.profiles.active"] = "apidoc"
  bootRun.jvmArgs("-Dspring.profiles.active=apidoc")
}
```

The `BootRun.jvmArgs()` method _adds_ JVM arguments; you can call it multiple times if you need to.

**Comment by mhornung-chwy** [comment]
The problem with some of the other answers here is that it modifies the `bootRun` task to always run with the profile you want to use to generate the API docs. A workaround to that is this:

1. Modify the `bootRun` task to pass all the command line properties through.

```
// Kotlin
tasks.bootRun {
    systemProperties(System.getProperties().mapKeys { it.key as String })
}
```

2. Specify the Spring profile on the arguments.

```
./gradlew generateOpenApiDocs -Dspring.profiles.active=apidocs
```

**Comment by caspianb** [comment]
@mhornung-chwy I do not believe that works if you wish to trigger doc generation as part of a greater process (e.g. generateOpenApiDocs dependsOn, etc).

As far as I can tell, there is no viable "workaround" for the missing forkProperties parameter; it would be very helpful if some form of equivalent option were reinstated. We are currently stuck on the older version because of this (unless there is some method to ingest specific environment variables into a specific task directly inside the gradle files?).

**Comment by mhornung-chwy** [comment]
@caspianb Here's another workaround.

First, register the new task that depends on the API docs generation and does whatever else it needs to do.

```
tasks.register<DefaultTask>("someTask") {
    dependsOn("generateOpenApiDocs")
}
```

Modify bootRun to ingest any system properties that are set.

```
tasks.bootRun {
    systemProperties(System.getProperties().mapKeys { it.key as String })
}
```

Create a new task to set the `spring.profiles.active` system property.

```
tasks.register<DefaultTask>("systemPropsTask") {
    System.setProperty("spring.profiles.active", "apidocs")
}
```

Lastly, make the API spec generation depend on the task that sets the system properties.

```
tasks.withType<org.springdoc.openapi.gradle.plugin.OpenApiGeneratorTask> {
    dependsOn("systemPropsTask")
}
```
 
Run `./gradlew someTask` to generate the API spec, and continue with whatever else is set in the task.

**Comment by ericenns** [comment]
@caspianb here is another workaround. (note: this is all in kotlin DSL)

Add the following to top of `build.gradle.kts`
```kotlin
import org.springframework.boot.gradle.tasks.run.BootRun
```

Then create an openapi definition.

If you want to pass all system properties to bootRun do the following:
```kotlin
openApi {
    # your configuration here
    val bootRun = project.tasks.named("bootRun").get() as BootRun
    bootRun.systemProperties(System.getProperties().mapKeys { it.key as String }))
}
```

If you only want default system properties and allow them to be overridden, do the following:
```kotlin
openApi {
    # you config here
    val defaultSystemProperties = mapOf(
        "spring.profiles.active" to "dev,swagger"
    )
    val providedSystemProperties = System.getProperties().mapKeys { it.key as String }
    val filteredProvidedSystemProperties = providedSystemProperties.filterKeys { it in defaultSystemProperties}
    val bootRun = project.tasks.named("bootRun").get() as BootRun
    bootRun.systemProperties(defaultSystemProperties + filteredProvidedSystemProperties)
}
```

**Comment by thejeff77** [comment]
Seems like you guys are doing a lot of work around this issue when you could simply bump the version back to 1.3.3. 

What's the point of adding a bunch of additional code to maintain rather than waiting for a versioned release with a fix?

**Comment by litols** [comment]
Hi there, I faced to this issue too. to customize bootRun parameter, I've submit PR to supply custom properties.
I hope I can resolve this issue by this PR...

**Comment by juliaisnotavailable** [comment]
Non Kotlin workaround where you don't need to trigger doc generation as part of a greater process.

```
bootRun {
   systemProperties System.properties
}
```

`./gradlew generateOpenApiDocs -Dspring.profiles.active=openapi `
