### ISSUE TITLE
Impossible to export yaml files when there are several groups

### ISSUE THREAD

**Issue by benfonty** [springdoc/springdoc-openapi-gradle-plugin#76]
Hello, I am trying to export several groups in yaml format.

Here is my plugin configuration:

```
openApi {
    outputDir.set(file("$buildDir/docs"))
    groupedApiMappings.set(["http://localhost:8080/xxx/v3/api-docs.yaml/XXX public API": "openapi-xxx-public-api.yaml",
                            "http://localhost:8080/xxx/v3/api-docs.yaml/XXX admin API": "openapi-xxx-admin-api.yaml"])
    waitTimeInSeconds.set(100)
    bootRun {
        jvmArgs = ["-Dspring.profiles.active=openapigeneration"]
    }
}
```

I got an error: `> Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive`

I presume this is because of [`val isYaml = url.toLowerCase().matches(Regex(".+[./]yaml$"))`](https://github.com/springdoc/springdoc-openapi-gradle-plugin/blob/master/src/main/kotlin/org/springdoc/openapi/gradle/plugin/OpenApiGeneratorTask.kt#L77) which doesn't work when using groupedApiMappings because of the format of the urls.

**Comment by bnasslahsen** [comment]
@benfonty,

see the answer here https://github.com/springdoc/springdoc-openapi-gradle-plugin/issues/71

**Comment by bnasslahsen** [comment]
@benfonty, 

Are you able to provice a Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example)[](https://github.com/springdoc/springdoc-openapi/blob/231db66ef1c64d2ea5fe3ee84c39e31a8b331b70/CONTRIBUTING.adoc#reporting-security-vulnerabilities) that reproduces the problem ?

**Comment by benfonty** [comment]
I cloned the repo and added [a failing test](https://github.com/benfonty/springdoc-openapi-gradle-plugin/blob/bfonty/fix-yaml-group-generation/src/test/kotlin/org/springdoc/openapi/gradle/plugin/OpenApiGradlePluginTest.kt#L175).

I am not sure I will be able to propose a fix this morning but I will give it a try by monday.

**Comment by benfonty** [comment]
I found time to propose a PR to fix the problem.

It passed the unit tests I made and I also tested it "live" locally with the actual repo I had problem with.

**Comment by benfonty** [comment]
Hello @bnasslahsen can you find time to review my pull request?
