### ISSUE TITLE
Plugin is broken with Spring Boot 3.0.0-M3

### ISSUE THREAD

**Issue by kancsuki** [springdoc/springdoc-openapi-gradle-plugin#79]
Recently I updated from **SpringBoot 3.0.0-M2** to **M3**, and now my gradle build fails with the following message

`> Task with name 'bootRunMainClassName' not found in project ':myproject'.`

Probably the issue is related to this change: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M3-Release-Notes#simplifed-main-class-name-resolution-with-gradle

**Comment by bnasslahsen** [comment]
Thanks for your sharing @kancsuki,
This is related to spring-boot enhancements! And not springdoc!
