### ISSUE TITLE
Option to disable forkedSpringBootRun task

### ISSUE THREAD

**Issue by mmarusich** [springdoc/springdoc-openapi-gradle-plugin#83]
It would be great if we could disable forkedSpringBootRun execution during generateOpenApiDocs task.
We want to have control about who starting app, for example, we stating app in docker during or CI so we generateOpenApiDocs can do API call to docker container instead of staring app again during  forkedSpringBootRun

For now we disabling task in our gradle configuration:

`tasks.whenTaskAdded { task ->
    if (task.name.contains("forkedSpringBootRun")) {
        task.enabled = false
    }
}`

It would be great to have some configuration on plugin level, ex. `forkedRunEnabled:false` or something

**Comment by bnasslahsen** [comment]
@mmarusich, 

There are no plans for that.
Feel free to propose PR, if you believe it's useful for the community.
