### ISSUE TITLE
Lacking documentation about usage in Spring Framework without Spring Boot

### ISSUE THREAD

**Issue by scscgit** [springdoc/springdoc-openapi-gradle-plugin#84]
I'd like to request an improvement to the documentation to include an example of how this plugin can be used (to generate an OpenAPI spec file) for a Spring project that doesn't use Spring Boot -- especially for purposes of upgrading legacy projects.

All I found was an FAQ section named `12.62. How to Integrate Open API 3 with Spring project (not Spring Boot)?` on the https://springdoc.org/#how-to-integrate-open-api-3-with-spring-project-not-spring-boot page, but sadly, these steps are ambiguous, and I was unable to find any additional pointers that provide a feedback during the debugging effort.

With `id 'org.springdoc.openapi-gradle-plugin' version '1.3.3'` under `plugins`, this displays during the build:
```
Execution failed for task ':openapi:bootJar'.
> Failed to calculate the value of task ':openapi-api:bootJar' property 'mainClass'.
   > Main class name has not been configured and it could not be resolved
```

After disabling `bootJar`,
```gradle
bootJar {
  enabled = false
}
```
the following error is displayed instead,

```
Upload build version: my-version
Error: Could not find or load main class org.springframework.boot.loader.PropertiesLauncher
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.loader.PropertiesLauncher
<=========----> 72% EXECUTING [1m 6s]
> :openapi:generateOpenApiDocs
```
finishing with error `Unable to connect to http://localhost:8080/openapi waited for 120 seconds`, as the project is built, but the server isn't available.

Note: on newer version, `id 'org.springdoc.openapi-gradle-plugin' version '1.4.0'` under `plugins`, the previous error returns:
```
Failed to query the value of task ':openapi:bootRun' property 'mainClass'.
> Main class name has not been configured and it could not be resolved
```

---

📓 Note: as a separate problem, because this library requires a higher Gradle version,
```
An exception occurred applying plugin request [id: 'org.springdoc.openapi-gradle-plugin', version: '1.4.0']
> Failed to apply plugin [id 'org.springframework.boot']
   > Spring Boot plugin requires Gradle 6.8.x, 6.9.x, or 7.x. The current version is Gradle 5.?.?
```

one of the required steps was to configure a new Gradle submodule. After installing a wrapper with a higher version, e.g by running a `wrapper` task after adding

```gradle
task wrapper(type: Wrapper) {
  // You gotta build this module using its own `gradlew` to fix compatibility
  gradleVersion = '6.9'
}
```

I was able to build the submodule from a command line (from inside its directory) -- up to the abovementioned error. However, building the original project no longer works, because as long as `/settings.gradle` references `include(':openapi')`, it cannot be built. Removing this reference breaks the new submodule instead.

I'd appreciate if you could include a similar use-case in your documentation to illustrate best practices, because this certainly isn't the first, or the last time anyone faced a forward, or a backward incompatibility. Sadly, I don't know any other alternative plugins that could be used with old projects to generate OpenAPI during build time, leaving us with generating the file manually before each release.

---

### References to other related resources:
* https://stackoverflow.com/questions/59871209/how-to-integrate-open-api-3-with-spring-project-not-spring-boot-using-springdo

**Comment by bnasslahsen** [comment]
You need the spring-boot plugin
