### ISSUE TITLE
Running the plugin with the test classpath

### ISSUE THREAD

**Issue by typekpb** [springdoc/springdoc-openapi-gradle-plugin#88]
My spring-boot based app needs DB, message broker and other dependencies to sucessfully start.
What I've already achieved is to run the lightweight version, with custom application-test.properties, that are used during the junit-based test runs.

Is there a way to use test classpath for the plugin run in any way? As I'd then be able to use our test-specific profile => in memory DB only, etc. If so, can you share an example of such configuration with me? Btw. it might be worth to share it in the README.md file as well, as others might be also interested.

Thanks!

**Comment by Picazsoo** [comment]
Hi @typekpb, I will probably not help you, but I still want to paste this here to start some discussion at least.
I tried for the last several days to run the task with a custom jar added to the classpath. Without success.
However upon downgrading to v 1.3.3, I can successfully pass all the required JVM parameters without issue:
My abbreviated build.gradle.kts looks like this:
```
...
val localDatabase: Configuration by configurations.creating

dependencies {
...
    localDatabase("com.h2database:h2")
    testImplementation("com.h2database:h2")
...
}
...

openApi {
    forkProperties.set("-Dloader.path=${localDatabase.files.first().parent} -Dspring.profiles.active=openapi")
}
...
```

And this works fine for me. It would be great if the same functionality was available also in the later versions of the plugin. Or maybe I am just doing something incorrectly...

**Comment by Picazsoo** [comment]
Hi @typekpb, just an update from my side. I was able to include the H2 jar on the classpath by defining it additionally also as  `developmentOnly("com.h2database:h2")` dependency. This means that the jar is available when running the `bootRun` task, but does not get packaged into the fat jar. I still need to have a separate `application-openapi.properties` defined in the standard sources that pretty closely mirrors the `application-test.properties` file but at least I am able to get it to work with the current version.
