### ISSUE TITLE
Plugin not compatible with upcoming Spring Boot 3

### ISSUE THREAD

**Issue by stuaeb** [springdoc/springdoc-openapi-gradle-plugin#94]
It seems that in Spring Boot, the bootRunMainClassName task has been removed or renamed:

Caused by: org.gradle.api.UnknownTaskException: Task with name 'bootRunMainClassName' not found in root project 'xxx'.
	at org.gradle.api.internal.tasks.DefaultTaskCollection.createNotFoundException(DefaultTaskCollection.java:102)
	at org.gradle.api.internal.tasks.DefaultTaskCollection.createNotFoundException(DefaultTaskCollection.java:46)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection.named(DefaultNamedDomainObjectCollection.java:360)
	at org.gradle.api.internal.tasks.DefaultTaskCollection.named(DefaultTaskCollection.java:112)

**Comment by faha1Ex** [comment]
I face the same problem and had to remove the plugin completely in order to prepare for the upcoming Spring Boot 3.0 release.

**Comment by faha1Ex** [comment]
Seems like the task was renamed to 'resolveMainClassName' in Spring Boot 3.0.
I am currently investigating locally and try to get it working again while upgrading an application to Spring Boot 3.0.

It is also connected to this issue, why was this not followed up? The mentioned workaround also does not work for me #79 

Are there any plans to support this change officially? Like with a new version dedicated only for Spring Boot 3.0? 
Or by conditionally choosing based on the Spring Boot Gradle plugin version? (Honestly, I have not clue if this is easily possible)
We really love the plugin and would also like to continue using it in the future :)

**Comment by cpoyatos1** [comment]
+1

**Comment by vsvyatski** [comment]
I'm experiencing the same issue here.

**Comment by schleichardt** [comment]
I added as workaround in build.gradle:

```groovy
task bootRunMainClassName { // workaround for https://github.com/springdoc/springdoc-openapi-gradle-plugin/issues/94
    doLast {
        springBoot.mainClassName
    }
}
```

**Comment by armogur** [comment]
> I added as workaround in build.gradle:
> 
> ```groovy
> task bootRunMainClassName { // workaround for https://github.com/springdoc/springdoc-openapi-gradle-plugin/issues/94
>     doLast {
>         springBoot.mainClassName
>     }
> }
> ```

This partly solved my problem, that means I could build the project, which is good, but when I want to generate API with this command:
`./gradlew clean generateOpenApiDocs`

I got another issue:
> Querying the mapped value of task ':resolveMainClassName' property 'outputFile' before task ':resolveMainClassName' has completed is not supported

Anyone can suggest on how to fix this?

**Comment by schleichardt** [comment]
I tried

```
bootRun {
    mainClass = "package.to.Main"
}
```

to get rid of the `'outputFile' ` error, but then I got a ` java.lang.ClassNotFoundException` for my Main class even though `./gradlew bootRun` works.

**Comment by vsvyatski** [comment]
Well, this issue helped me to realize that I don't really use this plug-in, I simply added it to my project for I had _springdoc-openapi-ui_ artifact leveraged. At the moment I believed that was sort of necessary, it appeared it isn't. So I just removed the plug-in and everything worked.

**Comment by steklopod** [comment]
+1

**Comment by lubumbax** [comment]
Any chance to make it work for Kotlin/build.gradle.kts?

**Comment by steklopod** [comment]
> Any chance to make it work for Kotlin/build.gradle.kts?

It already works for kotlin. But not for spring 6

**Comment by jord1e** [comment]
> > > Any chance to make it work for Kotlin/build.gradle.kts?
> > 
> > 
> > It already works for kotlin. But not for spring 6
> 
> As the title goes "Plugin not compatible with upcoming Spring Boot 3" (which requires Spring 6), any chance to make the fix work for both Java and Kotlin?
> 
> And regarding the workaround above for `gradle.build`, any chance to make that work for Kotlin's `gradle.build.kts`?:
> 
> ```
> task bootRunMainClassName { // workaround for https://github.com/springdoc/springdoc-openapi-gradle-plugin/issues/94
>     doLast {
>         springBoot.mainClassName
>     }
> }
> ```

Just needed this...:

```kotlin
tasks.create("bootRunMainClassName") { // workaround for https://github.com/springdoc/springdoc-openapi-gradle-plugin/issues/94
    doLast {
        springBoot.mainClass.get()
    }
}
```

**Comment by pplmx** [comment]
FYI. I tried this, works fine now.
```groovy
tasks.register('bootRunMainClassName')
```

**Comment by simonhauck** [comment]
In my case adding the task descripted in the answer from @pplmx  and @jord1e was not enough.
I got the following error `Querying the mapped value of task ':server:resolveMainClassName' property 'outputFile' before task ':server:resolveMainClassName' has completed is not supported`

But adding this did the trick for `build.gradke.kts` and SpringBoot 3.0

`````
tasks.create("bootRunMainClassName") {
    dependsOn(tasks.resolveMainClassName)
}

**Comment by steklopod** [comment]
Another PR https://github.com/springdoc/springdoc-openapi-gradle-plugin/pull/97 without breaking back compatibility with Spring Boot 2

**Comment by hrstoyanov** [comment]
Any chance this gets  fixed ASAP? 
Folks upgrading to Spring 3.x will waste a lot of time wondering what  is wrong with their Gradle build, and for some reason a  Google search on the error message does not find this thread (for workarounds)

**Comment by armogur** [comment]
@hrstoyanov :
> Any chance this gets fixed ASAP? This has been open for almost a month ...

I have this gradle plugin:
```groovy
id 'org.springdoc.openapi-gradle-plugin' version '1.5.0'
```

This dependency (notice the version: **2.0.0**):
```groovy
implementation group: 'org.springdoc', name: 'springdoc-openapi-starter-webmvc-ui', version: '2.0.0'
```
This workaround:
```groovy
tasks.create("bootRunMainClassName") {
    dependsOn(tasks.resolveMainClassName)
}
```

And this OpenAPI config:
```groovy
openApi {
    apiDocsUrl.set("http://localhost:8080/v3/api-docs.yaml")
    outputFileName.set("api-contract.yaml")
}
```

And then just running this command below generates the API contract: **build/api-contract.yaml**
```bash
./gradlew clean generateOpenApiDocs
```

**Comment by steklopod** [comment]
The PR https://github.com/springdoc/springdoc-openapi-gradle-plugin/pull/97 is waiting to be merged for fixing this issue.

- Tested in GitHub actions on Java 11, 17.
<img width="383" alt="Снимок экрана 2022-12-12 в 20 33 10" src="https://user-images.githubusercontent.com/29500153/207137289-92fc4896-a543-45ff-8d5c-afaed66b96d1.png">

- Tested localy.
<img width="430" alt="Снимок экрана 2022-12-12 в 18 50 47" src="https://user-images.githubusercontent.com/29500153/207117660-668adfdc-a7a5-40b7-b059-8dc75802fbb4.png">

**Comment by lubumbax** [comment]
> @hrstoyanov :
> 
> I have this gradle plugin:
> 
> ```groovy
> id 'org.springdoc.openapi-gradle-plugin' version '1.5.0'
> ```
> 
> This dependency (notice the version: **2.0.0**):
> 
> ```groovy
> implementation group: 'org.springdoc', name: 'springdoc-openapi-starter-webmvc-ui', version: '2.0.0'
> ```
> 
> And then just running this command below generates the API contract: **build/api-contract.yaml**
> 
> ```shell
> ./gradlew clean generateOpenApiDocs
> ```

That for me results in (building with `build.gradle.kts`):
```
> Error while evaluating property 'filteredArgumentsMap' of task ':airportservice:compileKotlin'
   > Could not resolve all files for configuration ':airportservice:compileClasspath'.
      > Could not find org.springdoc:springdoc-openapi-webflux-ui:2.0.0.
```

Any idea what I may be missing?
