### ISSUE TITLE
groupedApiMappings cannot set a list

### ISSUE THREAD

**Issue by pplmx** [springdoc/springdoc-openapi-gradle-plugin#96]
## add the line `groupedApiMappings`,
`.\gradlew build` failed in the following:
![image](https://user-images.githubusercontent.com/26994103/205483288-1c31193b-4081-4793-84fc-f4f8598511d9.png)
![image](https://user-images.githubusercontent.com/26994103/205483308-b0bed1b2-916d-4ea7-aae0-3b81abb893ca.png)

## remove the line `groupedApiMappings`
![image](https://user-images.githubusercontent.com/26994103/205483426-02404944-a15f-4967-a112-b7157afcc83b.png)
![image](https://user-images.githubusercontent.com/26994103/205483495-28e12e7f-5195-471a-afc5-6f6460d94d4b.png)

## Others
```txt
Spring Boot: 3.0.0
Java Version: 19.0.1
```

**Comment by Rafaelsk** [comment]
I'm don't know gradle that very well, but I had the problem and I found a work around for it. I just replaced the the `to` with `:` operator

![image](https://user-images.githubusercontent.com/2865819/213476212-a76452f7-d13f-4765-8347-85c138c9dbfc.png)

That way it worked well for me. I hope this helps.

**Comment by pplmx** [comment]
Thanks. Works fine. :)
