### ISSUE TITLE
LocalDateTime is serialized to integer array by Jackson

### ISSUE THREAD

**Issue by ChrTall** [springdoc/springdoc-openapi-gradle-plugin#98]
A LocalDateTime field on my DTO is deserialized to a number Array by Jackson.

I would like to annotate the field so that the generated openapi.spec model has a number Array instead of a string.

This is the field on my DTO:
`@Schema(description = "The exact DateTime it was created. The date is a integer array: [yyyy, MM, dd, HH, mm, ss, SS]",
                example = "[2022, 10, 11, 14, 50, 20, 2525252]")
        LocalDateTime createdAtDateTime) `

The corresponding openapi.spec section is the following:
`"properties": {
          "createdAtDateTime": {
            "type": "string",
            "description": "The exact DateTime it was created. The date is a integer array: [yyyy, MM, dd, HH, mm, ss, SS]",
            "format": "date-time"
          }
        },`

**Comment by bnasslahsen** [comment]
Not related to `springdoc-openapi-gradle-plugin`
